Importing packages

In [ ]:
import numpy as np
import pandas as pd

Reading the dataset content path from drive

In [ ]:
var = pd.read_csv("/content/drive/MyDrive/Main project/DDOSDataset.csv")

In [ ]:
var

Unnamed: 0   Source Port   Destination Port   Protocol   Flow Duration  \
0            534           710              63567         17               2   
1          11527           711              23076         17               2   
2          19475           712              63593         17               1   
3          17750           713              60908         17               2   
4          26849           714              17757         17               1   
...          ...           ...                ...        ...             ...   
3994       28562           714              55976         17               1   
3995         984           715              32474         17               2   
3996       10843           716              14574         17               1   
3997       29634           717              63039         17               1   
3998        7903           718               2242         17               1   

       Total Fwd Packets  Total Length of Fwd Packets   Min Packet Length  \
0                      2                         1136                 568   
1                      2                         2944                1472   
2                      2                         2944                1472   
3                      2                         2944                1472   
4                      2                         2944                1472   
...                  ...                          ...                 ...   
3994                   2                         2944                1472   
3995                   2                         2944                1472   
3996                   2                         2944                1472   
3997                   2                         2944                1472   
3998                   2                         2944                1472   

       Max Packet Length   Average Packet Size   act_data_pkt_fwd  \
0                    568                 852.0                  1   
1                   1472                2208.0                  1   
2                   1472                2208.0                  1   
3                   1472                2208.0                  1   
4                   1472                2208.0                  1   
...                  ...                   ...                ...   
3994                1472                2208.0                  1   
3995                1472                2208.0                  1   
3996                1472                2208.0                  1   
3997                1472                2208.0                  1   
3998                1472                2208.0                  1   

       min_seg_size_forward Attack_type  
0                        32   DrDoS_DNS  
1                        32   DrDoS_DNS  
2                        32   DrDoS_DNS  
3                        32   DrDoS_DNS  
4                        32   DrDoS_DNS  
...                     ...         ...  
3994                    595  DrDoS_LDAP  
3995                    595  DrDoS_LDAP  
3996                    595  DrDoS_LDAP  
3997                    595  DrDoS_LDAP  
3998                    595  DrDoS_LDAP  

[3999 rows x 13 columns]

Converting categorical value into numerical value

In [ ]:
var['Attack_type'].replace({'DrDoS_DNS':1, 'DrDoS_LDAP':2, 'BENIGN':3}, inplace=True)
print(var)

      Unnamed: 0   Source Port   Destination Port   Protocol   Flow Duration  \
0            534           710              63567         17               2   
1          11527           711              23076         17               2   
2          19475           712              63593         17               1   
3          17750           713              60908         17               2   
4          26849           714              17757         17               1   
...          ...           ...                ...        ...             ...   
3994       28562           714              55976         17               1   
3995         984           715              32474         17               2   
3996       10843           716              14574         17               1   
3997       29634           717              63039         17               1   
3998        7903           718               2242         17               1   

       Total Fwd Packets  Total Length 

Splitting training and testing data

In [ ]:
x = var.iloc[:,:-1]
y = var.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder_x=LabelEncoder()
x = x.apply(LabelEncoder().fit_transform)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=0)

Bagging

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [ ]:
tree = DecisionTreeClassifier(max_depth=3, random_state=23)

In [ ]:
bagging = BaggingClassifier(base_estimator=tree, n_estimators=5, max_samples=50, bootstrap=True)

Training a Bagging Ensembling Model

In [ ]:
bagging.fit(x_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(max_depth=3,
                                                        random_state=23),
                  max_samples=50, n_estimators=5)

Making prediction

In [ ]:
p=bagging.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

Evaluating model

In [ ]:
print("\nAccuarcy_score : {:.2f} %".format(accuracy_score(y_test, p)*100))


Accuarcy_score : 89.75 %


In [ ]:
print("Classification report :\n",classification_report(y_test, p))

Classification report :
               precision    recall  f1-score   support

           1       0.91      0.98      0.94      1068
           2       0.58      0.24      0.34       131
           3       0.00      0.00      0.00         1

    accuracy                           0.90      1200
   macro avg       0.50      0.41      0.43      1200
weighted avg       0.88      0.90      0.88      1200



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print("Confusion Matrix :\n",confusion_matrix(y_test, p))

Confusion Matrix :
 [[1046   22    0]
 [ 100   31    0]
 [   1    0    0]]
