Importing packages

In [ ]:
import numpy as np
import pandas as pd

Reading the dataset content path from drive

In [ ]:
var = pd.read_csv("/content/drive/MyDrive/Main project/DDOSDataset.csv")

In [ ]:
var

Unnamed: 0   Source Port   Destination Port   Protocol   Flow Duration  \
0            534           710              63567         17               2   
1          11527           711              23076         17               2   
2          19475           712              63593         17               1   
3          17750           713              60908         17               2   
4          26849           714              17757         17               1   
...          ...           ...                ...        ...             ...   
3994       28562           714              55976         17               1   
3995         984           715              32474         17               2   
3996       10843           716              14574         17               1   
3997       29634           717              63039         17               1   
3998        7903           718               2242         17               1   

       Total Fwd Packets  Total Length of Fwd Packets   Min Packet Length  \
0                      2                         1136                 568   
1                      2                         2944                1472   
2                      2                         2944                1472   
3                      2                         2944                1472   
4                      2                         2944                1472   
...                  ...                          ...                 ...   
3994                   2                         2944                1472   
3995                   2                         2944                1472   
3996                   2                         2944                1472   
3997                   2                         2944                1472   
3998                   2                         2944                1472   

       Max Packet Length   Average Packet Size   act_data_pkt_fwd  \
0                    568                 852.0                  1   
1                   1472                2208.0                  1   
2                   1472                2208.0                  1   
3                   1472                2208.0                  1   
4                   1472                2208.0                  1   
...                  ...                   ...                ...   
3994                1472                2208.0                  1   
3995                1472                2208.0                  1   
3996                1472                2208.0                  1   
3997                1472                2208.0                  1   
3998                1472                2208.0                  1   

       min_seg_size_forward Attack_type  
0                        32   DrDoS_DNS  
1                        32   DrDoS_DNS  
2                        32   DrDoS_DNS  
3                        32   DrDoS_DNS  
4                        32   DrDoS_DNS  
...                     ...         ...  
3994                    595  DrDoS_LDAP  
3995                    595  DrDoS_LDAP  
3996                    595  DrDoS_LDAP  
3997                    595  DrDoS_LDAP  
3998                    595  DrDoS_LDAP  

[3999 rows x 13 columns]

Converting categorical value into numerical value

In [ ]:
var['Attack_type'].replace({'DrDoS_DNS':1, 'DrDoS_LDAP':2, 'BENIGN':3}, inplace=True)
print(var)

      Unnamed: 0   Source Port   Destination Port   Protocol   Flow Duration  \
0            534           710              63567         17               2   
1          11527           711              23076         17               2   
2          19475           712              63593         17               1   
3          17750           713              60908         17               2   
4          26849           714              17757         17               1   
...          ...           ...                ...        ...             ...   
3994       28562           714              55976         17               1   
3995         984           715              32474         17               2   
3996       10843           716              14574         17               1   
3997       29634           717              63039         17               1   
3998        7903           718               2242         17               1   

       Total Fwd Packets  Total Length 

Splitting training and testing data

In [ ]:
x = var.iloc[:,:-1]
y = var.iloc[:,-1].values

In [ ]:
x

Unnamed: 0   Source Port   Destination Port   Protocol   Flow Duration  \
0            534           710              63567         17               2   
1          11527           711              23076         17               2   
2          19475           712              63593         17               1   
3          17750           713              60908         17               2   
4          26849           714              17757         17               1   
...          ...           ...                ...        ...             ...   
3994       28562           714              55976         17               1   
3995         984           715              32474         17               2   
3996       10843           716              14574         17               1   
3997       29634           717              63039         17               1   
3998        7903           718               2242         17               1   

       Total Fwd Packets  Total Length of Fwd Packets   Min Packet Length  \
0                      2                         1136                 568   
1                      2                         2944                1472   
2                      2                         2944                1472   
3                      2                         2944                1472   
4                      2                         2944                1472   
...                  ...                          ...                 ...   
3994                   2                         2944                1472   
3995                   2                         2944                1472   
3996                   2                         2944                1472   
3997                   2                         2944                1472   
3998                   2                         2944                1472   

       Max Packet Length   Average Packet Size   act_data_pkt_fwd  \
0                    568                 852.0                  1   
1                   1472                2208.0                  1   
2                   1472                2208.0                  1   
3                   1472                2208.0                  1   
4                   1472                2208.0                  1   
...                  ...                   ...                ...   
3994                1472                2208.0                  1   
3995                1472                2208.0                  1   
3996                1472                2208.0                  1   
3997                1472                2208.0                  1   
3998                1472                2208.0                  1   

       min_seg_size_forward  
0                        32  
1                        32  
2                        32  
3                        32  
4                        32  
...                     ...  
3994                    595  
3995                    595  
3996                    595  
3997                    595  
3998                    595  

[3999 rows x 12 columns]

In [ ]:
y

array([1, 1, 1, ..., 2, 2, 2])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder_x=LabelEncoder()
x = x.apply(LabelEncoder().fit_transform)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=0)

In [ ]:
x_train

Unnamed: 0   Source Port   Destination Port   Protocol   Flow Duration  \
2539        1457           195               2373          1               1   
332         1734            21               3559          1               1   
852         2710            30               1487          1               1   
1036        1838           212               2293          1              29   
503         1554           192               1296          1               1   
...          ...           ...                ...        ...             ...   
835         3094            13               3389          1               1   
3264        3806           412               2889          1               1   
1653        2086           323               2267          1               1   
2607         522           266               3208          1               1   
2732        2266           391               1723          1               1   

       Total Fwd Packets  Total Length of Fwd Packets   Min Packet Length  \
2539                   0                          131                 131   
332                    0                          128                 128   
852                    0                          131                 131   
1036                   0                          131                 131   
503                    0                          131                 131   
...                  ...                          ...                 ...   
835                    0                          131                 131   
3264                   0                          131                 131   
1653                   0                          131                 131   
2607                   0                          131                 131   
2732                   0                          131                 131   

       Max Packet Length   Average Packet Size   act_data_pkt_fwd  \
2539                 131                   132                  0   
332                  128                   129                  0   
852                  131                   132                  0   
1036                 131                   132                  0   
503                  131                   132                  0   
...                  ...                   ...                ...   
835                  131                   132                  0   
3264                 131                   132                  0   
1653                 131                   132                  0   
2607                 131                   132                  0   
2732                 131                   132                  0   

       min_seg_size_forward  
2539                      3  
332                       1  
852                       4  
1036                      3  
503                       4  
...                     ...  
835                       1  
3264                      1  
1653                      3  
2607                      3  
2732                      1  

[2799 rows x 12 columns]

In [ ]:
x_test

Unnamed: 0   Source Port   Destination Port   Protocol   Flow Duration  \
3190        2624           337               2665          1               1   
1473        3357           141               2463          1               7   
3068        3316           215               3000          1               1   
1044        2575           220               2721          1               1   
3794        2840             1               2050          1               1   
...          ...           ...                ...        ...             ...   
1902        2332            66               2857          1               1   
1644        3263           314               3023          1               1   
149          948           349                689          1               1   
1471        1354           139                802          1               1   
1501        1701           170               1845          1               1   

       Total Fwd Packets  Total Length of Fwd Packets   Min Packet Length  \
3190                   0                          131                 131   
1473                   0                          131                 131   
3068                   0                          115                 115   
1044                   0                          131                 131   
3794                   0                          131                 131   
...                  ...                          ...                 ...   
1902                   0                          131                 131   
1644                   0                          130                 130   
149                    0                          130                 130   
1471                   0                          131                 131   
1501                   0                          128                 128   

       Max Packet Length   Average Packet Size   act_data_pkt_fwd  \
3190                 131                   132                  0   
1473                 131                   132                  0   
3068                 115                   116                  0   
1044                 131                   132                  0   
3794                 131                   132                  0   
...                  ...                   ...                ...   
1902                 131                   132                  0   
1644                 130                   131                  0   
149                  130                   131                  0   
1471                 131                   132                  0   
1501                 128                   129                  0   

       min_seg_size_forward  
3190                      3  
1473                      3  
3068                      1  
1044                      3  
3794                      1  
...                     ...  
1902                      3  
1644                      3  
149                       4  
1471                      3  
1501                      3  

[1200 rows x 12 columns]

In [ ]:
y_train

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
y_test

array([1, 1, 1, ..., 1, 1, 1])

Training a SVM Model

In [ ]:
from sklearn.svm import SVC
SVCclassifier = SVC(kernel='linear',random_state=2)
SVCclassifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=2)

In [ ]:
svc_pred = SVCclassifier.predict(x_test)

In [ ]:
svc_pred

array([1, 1, 1, ..., 1, 1, 1])

Evaluating SVM model

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
c=accuracy_score(y_test,svc_pred)
print("Accuracy of SVM model: {:.2f} %".format((c)*100))

Accuracy of SVM model: 88.42 %


In [ ]:
print(classification_report(y_test,svc_pred))

              precision    recall  f1-score   support

           1       0.90      0.98      0.94      1068
           2       0.39      0.11      0.18       131
           3       1.00      1.00      1.00         1

    accuracy                           0.88      1200
   macro avg       0.76      0.70      0.71      1200
weighted avg       0.85      0.88      0.85      1200



Training a KNN Model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
KNNclassifier = KNeighborsClassifier(n_neighbors=3)
KNNclassifier.fit(x_train, y_train)
KNN_pred = KNNclassifier.predict(x_test)

In [ ]:
KNN_pred

array([1, 1, 1, ..., 1, 1, 1])

Evaluating KNN model

In [ ]:
accuracy = accuracy_score(y_test, KNN_pred)
print("Accuracy of the KNN: {:.2f} %".format((accuracy)*100))

Accuracy of the KNN: 87.92 %


In [ ]:
print(classification_report(y_test, KNN_pred))

              precision    recall  f1-score   support

           1       0.90      0.98      0.93      1068
           2       0.33      0.10      0.15       131
           3       0.00      0.00      0.00         1

    accuracy                           0.88      1200
   macro avg       0.41      0.36      0.36      1200
weighted avg       0.84      0.88      0.85      1200



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Training Random Forest Classifier Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
RFclassifier = RandomForestClassifier(n_estimators = 10, max_depth = 4, max_features = 3, bootstrap = True, random_state = 18).fit(x_train, y_train)

In [ ]:
RF_pred = RFclassifier.predict(x_test)

In [ ]:
RF_pred

array([1, 1, 1, ..., 1, 1, 1])

Evaluating Model

In [ ]:
a=accuracy_score(y_test, RF_pred)
print("Accuracy of Random forest: {:.2f} %".format((a)*100))

Accuracy of Random forest: 90.50 %


In [ ]:
print(classification_report(y_test,RF_pred))

              precision    recall  f1-score   support

           1       0.90      1.00      0.95      1068
           2       1.00      0.14      0.24       131
           3       0.00      0.00      0.00         1

    accuracy                           0.91      1200
   macro avg       0.63      0.38      0.40      1200
weighted avg       0.91      0.91      0.87      1200



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Averaging

In [ ]:
ensemble_pred = (svc_pred + KNN_pred + RF_pred)//3

In [ ]:
ensemble_acc = accuracy_score(y_test, ensemble_pred)

In [ ]:
print("Ensemble accuracy: {:.2f} %".format((ensemble_acc)*100))

Ensemble accuracy: 89.00 %
